# Parameters for the Behavior Planner and Pure Pursuit Controller

# Pure Pursuit Controller Parameters
pp_params:
  wheelbase: 0.324
  lookahead_min: 0.3
  lookahead_max: 1.5
  max_steering_angle_deg: 30.0
  lookahead_speed_gain: 0.5
  lookahead_curvature_gain: 0.1

# Vehicle Speed Limit
vmax: 6.0

# Safety Thresholds
safety_thresholds:
  min_free_distance: 2.0

# Cost Fusion Parameters for Lane Selection
cost_fusion_params:
  weights:
    alpha: 2.0   # free_distance
    beta: 1.0    # curvature
    gamma: 1.0   # progress
    delta: 0.3   # lane_change_penalty
    w_lane: 0.5  # vlm_lane_hint
    zeta: 0.4    # center_lane_preference
  epsilon: 1.0e-6

# Paths for lane data CSV files
lane_csv_paths:
  center: "/home/autodrive_devkit/src/simulator_LLM/car_control/CSVs/Centerline_points.csv"
  inner: "/home/autodrive_devkit/src/simulator_LLM/car_control/CSVs/inner_bound_points.csv"
  outer: "/home/autodrive_devkit/src/simulator_LLM/car_control/CSVs/outer_bound_points.csv"

# VLM Advisor Parameters
vlm_params:
  camera_topic: "/autodrive/f1tenth_1/front_camera"
  api_base: "http://127.0.0.1:8000/v1"
  api_key: "EMPTY"
  model: "qwen2_5_vl"
  hz: 3.0
  timeout_s: 0.3  # Timeout for the VLM call
  conf_thresh: 0.5 # Confidence threshold
  jpeg_w: 640
  jpeg_h: 384
  jpeg_q: 80
  max_tokens: 120
  temperature: 0.1