# Parameters for the Behavior Planner and Pure Pursuit Controller

# Pure Pursuit Controller Parameters
pp_params:
  wheelbase: 0.324
  lookahead_min: 0.3
  lookahead_max: 1.5
  max_steering_angle_deg: 30.0
  lookahead_speed_gain: 0.5
  lookahead_curvature_gain: 0.1

# Speed Control Parameters
speed:
  vmax: 1.0      # The speed value that corresponds to 100% throttle (0.0-1.0 scale).
  default_speed: 0.10 # Target speed value, corresponds to 10% throttle (0.1).
  vmin: 0.05      # Minimum speed value, corresponds to 5% throttle (0.05).
  mu: 0.9        # Assumed friction coefficient for curvature calculations.
  obs_kd: 0.8    # Proportional gain for obstacle-based speed reduction.
  throttle_scale: 1.0 # Scale for throttle command. Use 1.0 for float percentage (0.0-1.0).
  # Curvature-based slowing parameters
  curvature_start_slowing: 0.2 # Curvature value to start slowing down.
  curvature_max_slowing: 1.0   # Curvature value to be at minimum speed.

# Safety Thresholds
safety_thresholds:
  min_free_distance: 2.0

# Cost Fusion Parameters for Lane Selection
cost_fusion_params:
  weights:
    alpha: 2.0   # free_distance
    beta: 1.0    # curvature
    gamma: 1.0   # progress
    delta: 0.3   # lane_change_penalty
    eta: 5.0     # curvature_lane_change_penalty_gain
    w_lane: 0.5  # vlm_lane_hint
    zeta: 0.4    # center_lane_preference
    max_hint_age_s: 2.0 # Max age of a VLM hint before its weight becomes 0
  epsilon: 1.0e-6

# Paths for lane data CSV files
lane_csv_paths:
  center: "/home/autodrive_devkit/src/simulator_LLM/car_control/CSVs/Centerline_points.csv"
  inner: "/home/autodrive_devkit/src/simulator_LLM/car_control/CSVs/inner_bound_points.csv"
  outer: "/home/autodrive_devkit/src/simulator_LLM/car_control/CSVs/outer_bound_points.csv"

# VLM Advisor Parameters
vlm_params:
  camera_topic: "/autodrive/f1tenth_1/front_camera"
  api_base: "http://127.0.0.1:8000/v1"
  api_key: "EMPTY"
  model: "qwen2_5_vl"
  timeout_s: 3.5  # Timeout for the VLM call
  conf_thresh: 0.5 # Confidence threshold
  jpeg_w: 640
  jpeg_h: 384
  jpeg_q: 80
  max_tokens: 120
  temperature: 0.1