pp:
  lookahead_min: 1.0         # m
  lookahead_max: 4.5
  lookahead_gain_vs_speed: 0.35
speed:
  vmax: 6.0                   # m/s
  mu: 0.9                     # 마찰 가정
  obs_kd: 0.8                 # 거리→감속 계수
risk:
  sector_angles: [-45, 45]    # 왼/정/오 구획 기준
  class_weights: {car: 1.0, cone: 0.6, person: 1.2}
fusion:
  alpha: 2.0
  beta: 1.0
  gamma: 1.0
  delta: 0.5
  w_lane: 0.5
  w_speed: 0.3
vlm:
  hz: 8
  timeout_ms: 80
  conf_thresh: 0.6
topics:
  ips: "/autodrive/f1tenth_1/ips"
  imu: "/autodrive/f1tenth_1/imu"
  steer_cmd: "/autodrive/f1tenth_1/steering_command"
  throttle_cmd: "/autodrive/f1tenth_1/throttle_command"
